#!/bin/bash

iospath="/Users/kevinchromik/development/fl-application-ios"
androidpath="/Users/kevinchromik/development/fl-application-android"
localizationspath="/Users/kevinchromik/development/mobile-localizations"

echo "Pull newest Android keys"
cd $androidpath
git pull

echo "Reset mobile localization copy"
cd $localizationspath
git checkout master
git reset --hard origin/master
git pull

echo "Copy iOS keys"
python scripts/ios_to_yaml.py -l en -i $iospath/Application/en.lproj/Localizable.strings > ios.yaml
echo "Copy Android keys"
python scripts/android_to_yaml.py -l en < $androidpath/Freeletics/src/main/res/values/strings.xml > android.yaml
echo "Merge keys"
python scripts/merge_yaml.py -1 ios.yaml -2 android.yaml -l en > merged.yaml

echo "Replacing 'en:' with 'eo:'"
cat merged.yaml | sed 's/en:/eo:/1' > input/eo.yml

read -p "Enter branch name: " branchname
git checkout -b $branchname

read -p "Enter the commit message: " commitmessage
git commit -m "$commitmessage" input/eo.yml
git push --set-upstream origin $branchname
echo "Go to Github and open your PR!"
